wiki/encyclopedia/urls.py
from django.urls import path, re_path
from . import util
from . import views
import random

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>/", views.page , name="page"),
    path("wiki/<str:title>/edit", views.edit_page , name="edit"),
    path("create_page/", views.create_page, name="create"),
    path("random/", views.random, name="random"),
    path("search/", views.search, name="search"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse

from random import choice
from . import util
from markdown2 import Markdown


def index(request):
    return render(request, "encyclopedia/index.html", {
        "title": "Encyclopedia",
        "page_title" : "All Pages",
        "entries": util.list_entries()
    })

def page(request, title):
    markdown = Markdown()
    list = util.list_entries()
    if title not in list:
        raise Http404("Page Not Found")
    else:
        return render(request, "encyclopedia/page.html", {
            "title_page": title,
            "content": markdown.convert(util.get_entry(title))
            })


def create_page(request):
    list = util.list_entries()
    if request.method == "POST":
        items = request.POST
        title = items.get("title")
        content = items.get("entry")
        if title in list:
            return render(request, "encyclopedia/create.html", {
            "title": title,
            "content": content,
            "error": """<div class='alert alert-danger' role='alert'>
                            Page Already Exists. Change the Title
                        </div>""",
        })
        else:
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:page", kwargs={"title" : title} ))
    else:
        return render(request, "encyclopedia/create.html")

def random(request):
    list = util.list_entries()
    r_title = choice(list)
    return HttpResponseRedirect(reverse("wiki:page", kwargs={"title" : r_title} ))

def edit_page(request, title):
    list = util.list_entries()
    list.remove(title)
    if request.method == "POST":
        items = request.POST
        new_title = items.get("title")
        content = items.get("entry")
        if new_title in list:
            return render(request, "encyclopedia/edit.html", {
            "title": title,
            "content": content,
            "error": """<div class='alert alert-danger' role='alert'>
                            Page Already Exists. Change the Title
                        </div>""",
        })
        else:
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:page", kwargs={"title" : title} ))
    else:
        return render(request, "encyclopedia/edit.html", {
            "title_page": title+":Edit",
            "title": title,
            "content": util.get_entry(title)
        })

def search(request):
    strs = []
    list = util.list_entries()
    if request.method == 'GET':
        search_title = request.GET.get("title")
        for each in list:
            if search_title.lower() == each.lower():
                return HttpResponseRedirect(reverse("wiki:page", kwargs={"title" : each} ))
            elif search_title.lower() in each.lower():
                strs.append(each)
        return render(request, "encyclopedia/index.html", {
            "title": "Search Results",
            "page_title": "Results for the search",
            "entries": strs,
            "if_none": "<h2>None Found</h2>"
        })
                

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a page
{% endblock %}

{% block body_title %}
    {{ error|safe }}
    <div class="alert alert-info" role="alert">
        Please write down your page in a markup language called Markdown. Read through <a href=>Github's Markdown guide</a> to get an understanding for how Markdown's syntax works.
    </div>
{% endblock %}

{% block body %}
    <form action="{% url 'wiki:create' %}" method="post">
        <div class="mb-3">
            {% csrf_token %}
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" placeholder="Title Of the Entry" name="title" value="{{ title }}" required>
        </div>
        <div class="mb-3">
            <label for="entry" class="form-label">Entry</label>
            <textarea type="text" class="form-control" id="entry" rows="auto" autocomplete="off" name="entry" required>{{ content }}</textarea>
        </div>
        <div class="row">
            <div class="col p-2 flex-grow-1">
            </div>
            <div class="col-2 p-2">
                <div class="col text-end">
                    <button type="submit" class="btn btn-outline-success">Submit</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title_page }}
{% endblock %}

{% block body_title %}
    {{ error|safe }}
    <div class="alert alert-info" role="alert">
        Please write down your page in a markup language called Markdown. Read through <a href=>Github's Markdown guide</a> to get an understanding for how Markdown's syntax works.
    </div>
{% endblock %}

{% block body %}
    <form action="{% url 'wiki:edit' title %}" method="post">
        <div class="mb-3">
            {% csrf_token %}
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" placeholder="Title Of the Entry" name="title" value="{{ title }}" required>
        </div>
        <div class="mb-3">
            <label for="entry" class="form-label">Entry</label>
            <textarea type="text" class="form-control" id="entry" rows="auto" autocomplete="off" name="entry" required>{{ content }}</textarea>
        </div>
        <div class="row">
            <div class="col p-2 flex-grow-1">
            </div>
            <div class="col-2 p-2">
                <div class="col text-end">
                    <button type="submit" class="btn btn-outline-success">Submit</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body_title %}
    <h1 class="text-decoration-underline">{{ page_title }}</h1>
{% endblock %}

{% block body %}
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:page' entry %}">{{ entry }}</a></li>
            {% empty %}
            <li>{{ if_none|safe }}</li>
        {% endfor %}
    </ul>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'encyclopedia/styles.css' %}">
    <link rel="stylesheet" href="{% static 'encyclopedia/bootstrap.min.css' %}">
</head>
<body class="bg-primary bg-opacity-10">
    <header class="my-2">
        <div class="container border-bottom border-2">
            <div class="row">
                <div class="col-3 px-5 text-end">
                    <a href="{% url 'wiki:index' %}"><h1 style="color: white;">WIKI</h1></a>
                </div>
                <div class="col-9 bg-primary bg-opacity-25">
                    <div class="navbar bg-body-light">
                        <div class="container-fluid justify-content-center">
                            <form action="{% url 'wiki:search' %}" class="d-flex" role="search" method="get"  >
                                <input class="form-control ms-auto p-2" type="search" placeholder="Search" aria-label="Search" name="title">
                                <button class="btn btn-outline-light ms-2 p-2" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main class="my-4">
        <div class="container">
            <div class="row">
                <div class="col-md-3 border-end border-2 text-center py-3 bg-primary bg-opacity-25">
                    <div class="container">
                        <div class="row d-inline">
                            <a href="{% url 'wiki:index' %}" class="btn btn-outline-light btn-sm my-2 p-2">Home</a>
                        </div>
                        <div class="row d-inline">
                            <a href="{% url 'wiki:create' %}" class="btn btn-outline-light btn-sm my-2 p-2">Create Page</a>
                        </div>
                        <div class="row d-inline">
                            <a href="{% url 'wiki:random' %}" class="btn btn-outline-light btn-sm my-2 p-2">Random Page</a>
                        </div>
                        <div class="row d-inline">
                            <a href="" class="btn btn-outline-light btn-sm my-2 p-2">About Me</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="container border border-2 border-white p-5">
                        <div class="row">
                            <div class="container">
                                <div class="row justify-content-end">
                                    {% block body_title %}{% endblock %}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            {% block body %}{% endblock %}
                        </div>
                        <div class="row">
                            <div class="container">
                                <div class="row justify-content-between">
                                    {% block edit-page %}{% endblock %}
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </main>
</body>
</html>




wiki/encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title_page }}
{% endblock %}

{% block body_title %}
    <div class="col-3 text-end">
        <a href="{% url 'wiki:edit' title_page %}" class="btn btn-outline-danger">Edit Page</a>
    </div>
{% endblock %}

{% block body %}
    <style>
        h1{
            text-decoration: underline;
        }
    </style>
    {% autoescape off %}
        {{ content }}
    {% endautoescape %}
{% endblock %}